name: Upload Documentation

on:
    push:
        branches: [main]
        
        paths:
            - 'server/**'

    pull_request:
        branches:
            - main
        paths:
            - 'server/**'

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: server
        steps:
        -   name: Check out repository
            uses: actions/checkout@v2

        -   name: Set up Node.js
            uses: actions/setup-node@v2
            with:
                node-version: 18
            
        -   name: Install dependencies
            run: npm install
        
        -   name: Generate documentation with TypeDoc
            run: npx typedoc

        -   name: Commit and Push Documentation
            run: |
                git checkout docs
                git config user.name 'Github Actions'
                git config user.email 'actions@github.com'
                git add docs/
                git commit -m "Updated documentation" -a || echo "No changes to commit"
                git push origin docs

